### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by moiling** [XAY1/RedRockVocationHomework#1]
总得来说模仿得很像，嘛……MD风格
提一点小意见吧
- 1.Edit页面的status bar颜色是不是不对，估计是设置了透明色
- 2.创建的时候什么都不输入都可以创建……控制一下吧
- 3.每次跳转的时候都会屏幕一黑，下一个Activity缩放出来，说明你每次都把前一个Activity给杀掉了，然后返回的时候没用finish而是startActivity。你的意图可能是为了重新打开Activity让数据重新刷一遍，其实你可以使用startActivityForResult，然后在onActivityResult回调里面实现数据的刷新。

**Comment by XAY1** [comment]
@moiling 
学姐你看的真仔细，我居然都没有发现这些问题，我现在已经把问题全都改正了，你有空再去看看吧。^_^      

1.我的手机系统默认设置了沉浸式状态栏，所以在手机上调试的时候并没有发现Edit页面的status Bar是一个白条，后来把style（v21）中的“statusBarColor”修改后就完美解决了（果然是设成了透明色的锅，可是我搞不懂为什么设成了透明色就是一个白条呢？）。  
2.不输入内容都可以创建是因为调试的时候用着方便，后来居然忘了设置了(⊙﹏⊙)。  
3.原来startActivityForResult和onActivityResult是这么用的，之前真不知道，受教了^_^。
 http://pan.baidu.com/s/1c1qn7va

**Comment by XAY1** [comment]
#
